### ISSUE TITLE
Fabric server 0.7.1, won't even load spark-fabric (build 172)

### ISSUE THREAD

**Issue by Panderine** [lucko/spark#101]
This is the  server console error:

`[init] Starting the Minecraft server...,
[22:29:36] [main/INFO]: Loading for game Minecraft 1.16.5,
[22:29:36] [main/FATAL]: A critical error occurred,
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: spark requires {fabric @ [*]},
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:180) ~[fabric-server-launch.jar:?],
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-server-launch.jar:?],
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabric-server-launch.jar:?],
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [fabric-server-launch.jar:?],
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-server-launch.jar:?],
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?],
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?],
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?],
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?],
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?],
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?],
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?],
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?],
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?,
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?],
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?],
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-server-launch.jar:?],
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?],
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:177) ~[fabric-server-launch.jar:?],
	... 12 more,
`

**Comment by Panderine** [comment]
Solved by adding Fabric API jar. Apparently it's needed but not mentioned anywhere.
