### ISSUE TITLE
NoClassDefFoundError by any command

### ISSUE THREAD

**Issue by SlimeDog** [lucko/spark#112]
Spigot 1.16.5-3048 or Paper 1.16.5-624
Spark 1.5.2-b193

```
>spark healthreport
[15:36:52] [Craft Scheduler Thread - 18/WARN]: [spark] Plugin spark v1.5.2 generated an exception while executing task 391
java.lang.NoClassDefFoundError: me/lucko/spark/lib/adventure/nbt/TagStringIO
        at me.lucko.spark.lib.adventure.text.serializer.gson.legacyimpl.NBTLegacyHoverEventSerializerImpl.<clinit>(NBTLegacyHoverEventSerializerImpl.java:43) ~[?:?]
        at me.lucko.spark.lib.adventure.text.serializer.gson.legacyimpl.NBTLegacyHoverEventSerializer.get(NBTLegacyHoverEventSerializer.java:43) ~[?:?]
        at me.lucko.spark.lib.adventure.text.serializer.craftbukkit.BukkitComponentSerializer.<clinit>(BukkitComponentSerializer.java:55) ~[?:?]
        at me.lucko.spark.lib.adventure.platform.bukkit.BukkitFacet$Message.createMessage(BukkitFacet.java:67) ~[?:?]
        at me.lucko.spark.lib.adventure.platform.bukkit.BukkitFacet$Message.createMessage(BukkitFacet.java:59) ~[?:?]
        at me.lucko.spark.lib.adventure.platform.facet.FacetAudience.createMessage(FacetAudience.java:361) ~[?:?]
        at me.lucko.spark.lib.adventure.platform.facet.FacetAudience.sendMessage(FacetAudience.java:157) ~[?:?]
        at me.lucko.spark.lib.adventure.audience.ForwardingAudience.sendMessage(ForwardingAudience.java:65) ~[?:?]
        at me.lucko.spark.lib.adventure.audience.Audience.sendMessage(Audience.java:207) ~[?:?]
        at me.lucko.spark.lib.adventure.audience.Audience.sendMessage(Audience.java:183) ~[?:?]
        at me.lucko.spark.bukkit.BukkitCommandSender.sendMessage(BukkitCommandSender.java:57) ~[?:?]
        at me.lucko.spark.common.command.CommandResponseHandler.reply(CommandResponseHandler.java:81) ~[?:?]
        at me.lucko.spark.common.command.CommandResponseHandler.replyPrefixed(CommandResponseHandler.java:89) ~[?:?]
        at me.lucko.spark.common.command.modules.HealthModule.healthReport(HealthModule.java:135) ~[?:?]
        at me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:249) ~[?:?]
        at me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:203) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.5-3048.jar:3048-Spigot-a25e8ed-9db9aee]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.5-3048.jar:3048-Spigot-a25e8ed-9db9aee]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.spark.lib.adventure.nbt.TagStringIO
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.5-3048.jar:3048-Spigot-a25e8ed-9db9aee]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5-3048.jar:3048-Spigot-a25e8ed-9db9aee]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 21 more
```
Same issue with `spark tps`

**Comment by lucko** [comment]
Oops, thanks for reporting :)

**Comment by SlimeDog** [comment]
Confirmed fixed in build 194. Thanks.
