### ISSUE TITLE
[Bug] Console /spark cause "IllegalStateException: content must be set"

### ISSUE THREAD

**Issue by i0xHeX** [lucko/spark#13]
Reproduce:
1. Run `spark` command withing console.

Resources:
- spark b52
- Spigot 1.14 b2225
- Java 11.0.2 (Oracle JDK)

Versions affected: `b52`

```
[14:20:59] [Server thread/WARN]: Unexpected exception while parsing console command "spark"
org.bukkit.command.CommandException: Unhandled exception executing command 'spark' in plugin spark v1.3.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:692) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:433) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:397) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:953) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:798) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ExceptionInInitializerError
	at me.lucko.spark.common.SparkPlatform.executeCommand(SparkPlatform.java:108) ~[?:?]
	at me.lucko.spark.bukkit.SparkBukkitPlugin.onCommand(SparkBukkitPlugin.java:80) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	... 8 more
Caused by: java.lang.IllegalStateException: content must be set
	at net.kyori.text.TextComponent$Builder.build(TextComponent.java:291) ~[?:?]
	at me.lucko.spark.common.command.CommandResponseHandler.<clinit>(CommandResponseHandler.java:41) ~[?:?]
	at me.lucko.spark.common.SparkPlatform.executeCommand(SparkPlatform.java:108) ~[?:?]
	at me.lucko.spark.bukkit.SparkBukkitPlugin.onCommand(SparkBukkitPlugin.java:80) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	... 8 more
```

**Comment by lucko** [comment]
Fixed in latest commit
