### ISSUE TITLE
[Bug] Player /spark cause "java.lang.NoClassDefFoundError"

### ISSUE THREAD

**Issue by i0xHeX** [lucko/spark#14]
Reproduce:
1. Run `/spark` command in-game.

Resources:
- spark b52
- Spigot 1.14 b2225
- Java 11.0.2 (Oracle JDK)

Versions affected: `b52`

```
[14:21:21] [Server thread/INFO]: i0xHeX issued server command: /spark
[14:21:21] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'spark' in plugin spark v1.3.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:892) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:885) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:869) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class me.lucko.spark.common.command.CommandResponseHandler
	at me.lucko.spark.common.SparkPlatform.executeCommand(SparkPlatform.java:108) ~[?:?]
	at me.lucko.spark.bukkit.SparkBukkitPlugin.onCommand(SparkBukkitPlugin.java:80) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	... 17 more
```

**Comment by lucko** [comment]
Fixed in latest
