### ISSUE TITLE
Sponge version not launching

### ISSUE THREAD

**Issue by i9hdkill** [lucko/spark#15]
Spark Build 64:
SF 3711
Forge 2831
Console error:
https://pastebin.com/u4FbcGPw
Crash report:
https://pastebin.com/LibJqw8z

**Comment by md678685** [comment]
I can confirm this also occurs using the Velocity version:
```
[20:02:36] [main/INFO]: Booting up Velocity 1.0.0-SNAPSHOT (git-5524f3b7-b125)...
[20:02:36] [main/INFO]: Connections will use epoll channels, native (Linux amd64) compression, Java ciphers
[20:02:36] [main/INFO]: Loading plugins...
[20:02:38] [main/ERROR]: Can't create plugin spark
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NullPointerException
  at me.lucko.spark.velocity.SparkVelocityPlugin.<init>(SparkVelocityPlugin.java:62)
  while locating me.lucko.spark.velocity.SparkVelocityPlugin

1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226) ~[velocity.jar:1.0.0-SNAPSHOT (git-5524f3b7-b125)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053) ~[velocity.jar:1.0.0-SNAPSHOT (git-5524f3b7-b125)]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086) ~[velocity.jar:1.0.0-SNAPSHOT (git-5524f3b7-b125)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:78) ~[velocity.jar:1.0.0-SNAPSHOT (git-5524f3b7-b125)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:98) ~[velocity.jar:1.0.0-SNAPSHOT (git-5524f3b7-b125)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:220) ~[velocity.jar:1.0.0-SNAPSHOT (git-5524f3b7-b125)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:182) ~[velocity.jar:1.0.0-SNAPSHOT (git-5524f3b7-b125)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:41) ~[velocity.jar:1.0.0-SNAPSHOT (git-5524f3b7-b125)]
Caused by: java.lang.NullPointerException
	at me.lucko.spark.common.SparkPlatform.<init>(SparkPlatform.java:87) ~[?:?]
	at me.lucko.spark.velocity.SparkVelocityPlugin.<init>(SparkVelocityPlugin.java:56) ~[?:?]
	at me.lucko.spark.velocity.SparkVelocityPlugin$$FastClassByGuice$$5c7e0a13.newInstance(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[velocity.jar:1.0.0-SNAPSHOT (git-5524f3b7-b125)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity.jar:1.0.0-SNAPSHOT (git-5524f3b7-b125)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity.jar:1.0.0-SNAPSHOT (git-5524f3b7-b125)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[velocity.jar:1.0.0-SNAPSHOT (git-5524f3b7-b125)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050) ~[velocity.jar:1.0.0-SNAPSHOT (git-5524f3b7-b125)]
	... 6 more
[20:02:38] [main/INFO]: Loaded 8 plugins
```

Using Velocity build 125 and Spark build 64.
