### ISSUE TITLE
NullPointerException when trying to stop an active profiling task

### ISSUE THREAD

**Issue by freaky767** [lucko/spark#152]
```[19:59:29 INFO]: [⚡] The active profiler has been stopped! Uploading results...
[19:59:29 WARN]: Exception in thread "Craft Scheduler Thread - 4"
[19:59:29 WARN]: org.apache.commons.lang.UnhandledException: Plugin spark v1.7.0 generated an exception while executing task 744
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at me.lucko.spark.proto.SparkProtos$SystemStatistics$Java.setVendorVersion(SparkProtos.java:3752)
        at me.lucko.spark.proto.SparkProtos$SystemStatistics$Java.access$7800(SparkProtos.java:3623)
        at me.lucko.spark.proto.SparkProtos$SystemStatistics$Java$Builder.setVendorVersion(SparkProtos.java:3992)
        at me.lucko.spark.common.platform.PlatformStatisticsProvider.getSystemStatistics(PlatformStatisticsProvider.java:87)
        at me.lucko.spark.common.sampler.async.AsyncSampler.toProto(AsyncSampler.java:163)
        at me.lucko.spark.common.command.modules.SamplerModule.handleUpload(SamplerModule.java:308)
        at me.lucko.spark.common.command.modules.SamplerModule.profilerStop(SamplerModule.java:302)
        at me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:136)
        at me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:314)
        at me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:268)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

Spigot version: 1.8.8
Spark version: latest (1.7.0@bfbbcb3)

**Comment by lucko** [comment]
Thanks :)
