### ISSUE TITLE
[1.18.1 - 1.7.2] Crash possibly caused by spark?

### ISSUE THREAD

**Issue by Salamance73** [lucko/spark#165]
Hi I was getting some weird ticking player issues but now that I think I fixed the problem I'm getting an error that mentions spark in the first lines. I'm hoping you could help identify if its something I did wrong or not, thanks!

Description: Exception in server tick loop
```
java.lang.IllegalArgumentException: Tried to register duplicate PermissionNode 'spark.profiler'
	at net.minecraftforge.server.permission.events.PermissionGatherEvent$Nodes.addNodes(PermissionGatherEvent.java:96) ~[forge-1.18.1-39.0.10-universal.jar%23299!:?] {re:classloading,pl:eventbus:A}
	at me.lucko.spark.forge.plugin.ForgeServerSparkPlugin.onPermissionGather(ForgeServerSparkPlugin.java:122) ~[spark-forge.jar%23262!:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_2248_ForgeServerSparkPlugin_onPermissionGather_Nodes.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2337!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2337!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2337!:?] {}
	at net.minecraftforge.server.permission.PermissionAPI.initializePermissionAPI(PermissionAPI.java:137) ~[forge-1.18.1-39.0.10-universal.jar%23299!:?] {re:classloading}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:101) ~[forge-1.18.1-39.0.10-universal.jar%23299!:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:706) ~[preview_OptiFine_1.18.1_HD_U_H5_pre4.jar%23300!:?] {re:classloading}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:90) ~[client-1.18.1-20211210.034407-srg.jar%23295!:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:644) ~[client-1.18.1-20211210.034407-srg.jar%23295!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23295!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
```

**Comment by lucko** [comment]
Could you try using the latest version: https://spark.lucko.me/download

Stack trace seems to indicate the error occurs when the server is starting? is it an integrated server (running within the client) or a dedicated server?

**Comment by Salamance73** [comment]
its integrated. i think upon retry it worked and it was just me messing with nbt data or something. ill try updating and will let you know if it occurs again. thanks for the help.
