### ISSUE TITLE
[Bug] No more healthreport in system where spark can't get disk usage

### ISSUE THREAD

**Issue by mastermc05** [lucko/spark#166]
Before that, spark showed all the data but without the disk usage, and now it it just shows nothing, also seems like the reason why profiler don't want to stop and show the results, producing lots of lags, i'm fine with not seeing the disk usage, because maybe it's the policy in my host's OC, and i can see in the host's main page, but in that version it now broke everything
`java.lang.NullPointerException: Cannot invoke "java.nio.file.FileStore.getTotalSpace()" because "me.lucko.spark.common.monitor.disk.DiskUsage.FILE_STORE" is null
at me.lucko.spark.common.monitor.disk.DiskUsage.getTotal(DiskUsage.java:57) ~[spark.jar:?]
at me.lucko.spark.common.command.modules.HealthModule.addDiskStats(HealthModule.java:304) ~[spark.jar:?]
at me.lucko.spark.common.command.modules.HealthModule.healthReport(HealthModule.java:148) ~[spark.jar:?]
at me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:363) ~[spark.jar:?]
at me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:276) ~[spark.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1537]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.1.jar:git-Purpur-1537]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.1.jar:git-Purpur-1537]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by mastermc05** [comment]
thanks, last version works
