### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by dinobossytnew** [lucko/spark#171]
```
[13:34:52 INFO]: DinoBotsYT issued server command: /spark profiler
[13:34:52 INFO]: [⚡] Initializing a new profiler, please wait...
[13:34:53 INFO]: [⚡] Profiler now active! (async)
[13:34:53 INFO]: [⚡] Use '/spark profiler --stop' to stop profiling and upload the results.
[13:35:03 INFO]: DinoBotsYT issued server command: /spark profiler --stop
[13:35:03 INFO]: [⚡] The active profiler has been stopped! Uploading results...
[13:35:04 WARN]: [spark] Plugin spark v1.8.0 generated an exception while executing task 27005
java.lang.RuntimeException: Request was unsuccessful: 503 - 
        at me.lucko.spark.common.util.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:42) ~[?:?]
        at me.lucko.spark.common.util.BytebinClient.postContent(BytebinClient.java:80) ~[?:?]
        at me.lucko.spark.common.util.BytebinClient.postContent(BytebinClient.java:96) ~[?:?]
        at me.lucko.spark.common.command.modules.SamplerModule.handleUpload(SamplerModule.java:315) ~[?:?]
        at me.lucko.spark.common.command.modules.SamplerModule.profilerStop(SamplerModule.java:302) ~[?:?]
        at me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:136) ~[?:?]
        at me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:387) ~[?:?]
        at me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:300) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
``` IN GAME COMMAND /spark profiler is error.
paper spigot

**Comment by dinobossytnew** [comment]
1.16.5

**Comment by lucko** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503

Might've been a temporary blip with the server hosting bytebin - but it seems fine now. If the error happens again, it's most likely due to your servers internet connection.

I've also made a change (see above) which will ensure a copy of the profile is saved to disk if the error happens again in the future.
