### ISSUE TITLE
nullpointerexception in console after starting and cancelling profiler task

### ISSUE THREAD

**Issue by freaky767** [lucko/spark#199]
```
[21:01:14 INFO]: [⚡] The active profiler has completed! Uploading results...
[21:01:14 WARN]: java.lang.NullPointerException
[21:01:14 WARN]:        at me.lucko.spark.common.platform.serverconfig.AbstractServerConfigProvider.delete(AbstractServerConfigProvider.java:97)
[21:01:14 WARN]:        at me.lucko.spark.common.platform.serverconfig.AbstractServerConfigProvider.delete(AbstractServerConfigProvider.java:108)
[21:01:14 WARN]:        at me.lucko.spark.common.platform.serverconfig.AbstractServerConfigProvider.delete(AbstractServerConfigProvider.java:108)
[21:01:14 WARN]:        at me.lucko.spark.common.platform.serverconfig.AbstractServerConfigProvider.delete(AbstractServerConfigProvider.java:89)
[21:01:14 WARN]:        at me.lucko.spark.common.platform.serverconfig.AbstractServerConfigProvider.lambda$loadServerConfigurations$0(AbstractServerConfigProvider.java:59)
[21:01:14 WARN]:        at java.base/java.util.Map.forEach(Map.java:661)
[21:01:14 WARN]:        at me.lucko.spark.common.platform.serverconfig.AbstractServerConfigProvider.loadServerConfigurations(AbstractServerConfigProvider.java:55)
[21:01:14 WARN]:        at me.lucko.spark.common.platform.serverconfig.ServerConfigProvider.exportServerConfigurations(ServerConfigProvider.java:46)
[21:01:14 WARN]:        at me.lucko.spark.common.sampler.AbstractSampler.writeMetadataToProto(AbstractSampler.java:121)
[21:01:14 WARN]:        at me.lucko.spark.common.sampler.async.AsyncSampler.toProto(AsyncSampler.java:165)
[21:01:14 WARN]:        at me.lucko.spark.common.command.modules.SamplerModule.handleUpload(SamplerModule.java:308)
[21:01:14 WARN]:        at me.lucko.spark.common.command.modules.SamplerModule.lambda$profilerStart$3(SamplerModule.java:260)
[21:01:14 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
[21:01:14 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
[21:01:14 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[21:01:14 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[21:01:14 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[21:01:14 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[21:01:14 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
i recreated this by doing `/spark profiler --timeout 30` then immediately cancelling: `/spark profiler --cancel` and repeating the commands a few times

it infact also uploads multiple profiler results but they seem to be empty

**Comment by lucko** [comment]
Oops! thanks :)
