### ISSUE TITLE
Forge Mod Does not work

### ISSUE THREAD

**Issue by BradHunter** [lucko/spark#22]
```
> 18:34:10 [INFO] Starting minecraft server version 1.6.4
> 18:34:10 [INFO] Attempting early MinecraftForge initialization
> 18:34:10 [INFO] MinecraftForge v
> 18:34:10 [INFO] 9.11.1.965
> 18:34:10 [INFO] Initialized
> 18:34:10 [INFO] MinecraftForge v9.11.1.965 Initialized
> 18:34:11 [INFO] Replaced 111 ore recipies
> 18:34:11 [INFO] Completed early MinecraftForge initialization
> 18:34:11 [INFO] Reading custom logging properties from /home/container/config/logging.properties
> 18:34:11 [OFF] Logging level for ForgeModLoader logging is set to ALL
> > > > > > > 18:34:11 [INFO] Searching /home/container/mods for mods
> > > > > > > > > > > > 18:34:11 [SEVERE] Unable to read a class file correctly
java.lang.IllegalArgumentException
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at cpw.mods.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:52)
at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:72)
at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42)
at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71)
at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:134)
at cpw.mods.fml.common.Loader.identifyMods(Loader.java:341)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:472)
at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:94)
at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:366)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:93)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
> 18:34:11 [SEVERE] There was a problem reading the entry me/lucko/spark/forge/ForgeServerSparkPlugin.class in the jar /home/container/mods/spark-forge.jar - probably a corrupt zip
cpw.mods.fml.common.LoaderException: java.lang.IllegalArgumentException
at cpw.mods.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:58)
at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:72)
at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42)
at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71)
at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:134)
at cpw.mods.fml.common.Loader.identifyMods(Loader.java:341)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:472)
at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:94)
at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:366)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:93)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: java.lang.IllegalArgumentException
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at cpw.mods.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:52)
... 11 more
> 18:34:11 [WARNING] Zip file spark-forge.jar failed to read properly, it will be ignored
cpw.mods.fml.common.LoaderException: java.lang.IllegalArgumentException
at cpw.mods.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:58)
at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:72)
at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42)
at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71)
at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:134)
at cpw.mods.fml.common.Loader.identifyMods(Loader.java:341)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:472)
at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:94)
at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:366)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:93)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: java.lang.IllegalArgumentException
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at cpw.mods.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:52)
... 11 more
> 18:34:11 [INFO] Forge Mod Loader has identified 4 mods to load
> > > > > > > > 18:34:11 [INFO] Activating mod mcp
> > 18:34:11 [INFO] Activating mod FML
> > > 18:34:12 [INFO] Activating mod Forge
```

**Comment by md678685** [comment]
The Forge version only targets Forge for Minecraft 1.12.2 - it won't run on a 1.6.4 server without being ported to Forge for 1.6.4.
