### ISSUE TITLE
Missing "world" tab in created result

### ISSUE THREAD

**Issue by fire7d** [lucko/spark#222]
I dont know what informations do You need and I dont know how to properly report an issue.

When profiler is completed and result is uploading to website, I got an exception in console and there's no **world** tab.

Im using "latest" 1.8.8 paper commit, jre1.8.0_321 and im starting profiler using **/spark profiler --timeout 60**.

Example result with this problem: https://spark.lucko.me/QmeBLR9l5C

```
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: java.lang.NullPointerException
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at me.lucko.spark.proto.SparkProtos$WorldStatistics$Chunk$Builder.putEntityCounts(SparkProtos.java:10965)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at me.lucko.spark.common.platform.world.WorldStatisticsProvider.lambda$chunkToProto$2(WorldStatisticsProvider.java:125)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at java.util.Map.forEach(Unknown Source)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at me.lucko.spark.common.platform.world.WorldStatisticsProvider.chunkToProto(WorldStatisticsProvider.java:121)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at me.lucko.spark.common.platform.world.WorldStatisticsProvider.regionToProto(WorldStatisticsProvider.java:111)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at me.lucko.spark.common.platform.world.WorldStatisticsProvider.lambda$getWorldStatistics$0(WorldStatisticsProvider.java:91)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at java.util.HashMap.forEach(Unknown Source)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at me.lucko.spark.common.platform.world.WorldStatisticsProvider.getWorldStatistics(WorldStatisticsProvider.java:82)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at me.lucko.spark.common.platform.PlatformStatisticsProvider.getPlatformStatistics(PlatformStatisticsProvider.java:191)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at me.lucko.spark.common.sampler.AbstractSampler.writeMetadataToProto(AbstractSampler.java:135)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at me.lucko.spark.common.sampler.java.JavaSampler.toProto(JavaSampler.java:129)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at me.lucko.spark.common.command.modules.SamplerModule.handleUpload(SamplerModule.java:308)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at me.lucko.spark.common.command.modules.SamplerModule.lambda$profilerStart$3(SamplerModule.java:260)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[17:24:50] [ForkJoinPool.commonPool-worker-9/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by lucko** [comment]
Please could you try updating spark? :)

**Comment by fire7d** [comment]
It's working, thanks!
