### ISSUE TITLE
Sponge 8 spark crash

### ISSUE THREAD

**Issue by Kawa1Ares** [lucko/spark#226]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2022/7/12 下午12:18
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:71) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:37) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37) ~[forge-1.16.5-36.2.35.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49) [forge-1.16.5-36.2.35.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46) [forge-1.16.5-36.2.35.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:43) [forge-1.16.5-36.2.35.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at me.lucko.spark.sponge.Sponge8SparkPlugin.<init>(Sponge8SparkPlugin.java:89) ~[spark:?] {re:classloading}
-- MOD spark --
Details:
	Caused by 0: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/ErrorInjectingConstructor]: IllegalStateException: Server and client both unavailable
  at Sponge8SparkPlugin.<init>(Sponge8SparkPlugin.java:77)
  at PluginModule.configure(PluginModule.java:49)
  while locating Sponge8SparkPlugin

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
PluginModule:          "org.spongepowered.common.inject.plugin.PluginModule"
Sponge8SparkPlugin:    "me.lucko.spark.sponge.Sponge8SparkPlugin"
========================
End of classname legend:
========================

		at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:568) ~[?:?] {re:classloading}
		at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:190) ~[?:?] {re:classloading}
		at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113) ~[?:?] {re:classloading}
		at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:239) ~[?:?] {re:classloading}
		at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:244) ~[?:?] {re:classloading}
		at org.spongepowered.forge.launch.plugin.PluginModContainer.constructPlugin(PluginModContainer.java:62) ~[spongeforge:1.16.5-36.2.5-8.1.0-RC1153] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.spongeforge.core.json:minecraftforge.fml.ModContainerMixin_Forge,pl:mixin:A}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

	Mod File: spark-1.9.23-sponge8.jar
	Failure message: spark-sponge8 (spark) has failed to load correctly
		com.google.inject.CreationException: Unable to create injector, see the following errors:
		
		1) [Guice/ErrorInjectingConstructor]: IllegalStateException: Server and client both unavailable
		  at Sponge8SparkPlugin.<init>(Sponge8SparkPlugin.java:77)
		  at PluginModule.configure(PluginModule.java:49)
		  while locating Sponge8SparkPlugin
		
		Learn more:
		  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
		
		1 error
		
		======================
		Full classname legend:
		======================
		PluginModule:          "org.spongepowered.common.inject.plugin.PluginModule"
		Sponge8SparkPlugin:    "me.lucko.spark.sponge.Sponge8SparkPlugin"
		========================
		End of classname legend:
		========================
		
	Mod Version: 1.9.23
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.IllegalStateException: Server and client both unavailable
Stacktrace:
	at me.lucko.spark.sponge.Sponge8SparkPlugin.<init>(Sponge8SparkPlugin.java:89) ~[spark:?] {re:classloading}
	at me.lucko.spark.sponge.Sponge8SparkPlugin$$FastClassByGuice$$25318778.GUICE$TRAMPOLINE(<generated>) ~[?:?] {}
	at me.lucko.spark.sponge.Sponge8SparkPlugin$$FastClassByGuice$$25318778.apply(<generated>) ~[?:?] {}
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[?:?] {re:classloading}
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[?:?] {re:classloading}
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[?:?] {re:classloading}
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[?:?] {re:classloading}
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[?:?] {re:classloading}
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[?:?] {re:classloading}
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) ~[?:?] {re:classloading}
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:214) ~[?:?] {re:classloading}
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186) ~[?:?] {re:classloading}
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113) ~[?:?] {re:classloading}
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:239) ~[?:?] {re:classloading}
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:244) ~[?:?] {re:classloading}
	at org.spongepowered.forge.launch.plugin.PluginModContainer.constructPlugin(PluginModContainer.java:62) ~[spongeforge:1.16.5-36.2.5-8.1.0-RC1153] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.spongeforge.core.json:minecraftforge.fml.ModContainerMixin_Forge,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 11.0.15, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
	Memory: 5045314976 bytes (4811 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 8
	JVM Flags: 4 total; -Xmx5G -Xms5G -XX:+UseG1GC -Xss512K
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.35.jar fml TRANSFORMATIONSERVICE 
		/spongeforge-1.16.5-36.2.5-8.1.0-RC1153-universal.jar spongeforge TRANSFORMATIONSERVICE 
		/spongeforge-1.16.5-36.2.5-8.1.0-RC1153-universal.jar superclass_change TRANSFORMATIONSERVICE 
		/spongeforge-1.16.5-36.2.5-8.1.0-RC1153-universal.jar access_widener TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.35
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		spongeapi@1.16.5-36.2.5-8.1.0-RC1153
		sponge@1.16.5-36.2.5-8.1.0-RC1153
		java_plain@1.16.5-36.2.5-8.1.0-RC1153
	Mod List: 
		forge-1.16.5-36.2.35-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		LuckPerms-Sponge-5.4.30.jar                       |LuckPerms                     |luckperms                     |5.4.30              |CREATE_REG|Manifest: NOSIGNATURE
		spark-1.9.23-sponge8.jar                          |spark-sponge8                 |spark                         |1.9.23              |ERROR     |Manifest: NOSIGNATURE
		null                                              |SpongeAPI                     |spongeapi                     |8.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		null                                              |Sponge                        |sponge                        |8.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-universal.jar                |Forge                         |forge                         |36.2.35             |CREATE_REG|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		spongeforge-1.16.5-36.2.5-8.1.0-RC1153-universal.j|SpongeForge                   |spongeforge                   |1.16.5-36.2.5-8.1.0-|CREATE_REG|Manifest: NOSIGNATURE
		worldedit-sponge-api8.0.0-7.2.9.jar               |WorldEdit                     |worldedit                     |7.2.9+e20e013       |CREATE_REG|Manifest: NOSIGNATURE
		Nucleus-3.0.0-BETA7-MC1.16.5-SpongeAPI8.1-plugin.j|Nucleus                       |nucleus                       |3.0.0-BETA7         |CREATE_REG|Manifest: NOSIGNATURE
	Crash Report UUID: 5bd9638e-0ab8-47c2-8b34-c48cac41f79c

**Comment by dimon7147** [comment]
Same problem, versions 1.9.15, 1.9.24, 1.9.25 do not work on Sponge API8.
Checked version 1.9.13, it works.

**Comment by Kawa1Ares** [comment]
> Same problem, versions 1.9.15, 1.9.24, 1.9.25 do not work on Sponge API8. Checked version 1.9.13, it works.

Thx! <3

**Comment by lucko** [comment]
36ac0700f6eaab4404b7dbca8537af8a6ac681a7

Thanks

**Comment by Kawa1Ares** [comment]
> [36ac070](https://github.com/lucko/spark/commit/36ac0700f6eaab4404b7dbca8537af8a6ac681a7)
> 
> Thanks

no problem！
