### ISSUE TITLE
RuntimeException after profiler task is stopped

### ISSUE THREAD

**Issue by freaky767** [lucko/spark#247]
Server: 1.8.8 spigot fork
Using Java 17
```
[22:07:59 WARN]: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.bukkit.Chunk.getX()" because "chunk" is null
[22:07:59 WARN]:        at me.lucko.spark.common.platform.world.WorldStatisticsProvider.getWorldStatistics(WorldStatisticsProvider.java:67)
[22:07:59 WARN]:        at me.lucko.spark.common.platform.PlatformStatisticsProvider.getPlatformStatistics(PlatformStatisticsProvider.java:193)
[22:07:59 WARN]:        at me.lucko.spark.common.sampler.AbstractSampler.writeMetadataToProto(AbstractSampler.java:135)
[22:07:59 WARN]:        at me.lucko.spark.common.sampler.async.AsyncSampler.toProto(AsyncSampler.java:165)
[22:07:59 WARN]:        at me.lucko.spark.common.command.modules.SamplerModule.handleUpload(SamplerModule.java:306)
[22:07:59 WARN]:        at me.lucko.spark.common.command.modules.SamplerModule.profilerStop(SamplerModule.java:300)
[22:07:59 WARN]:        at me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:134)
[22:07:59 WARN]:        at me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:382)
[22:07:59 WARN]:        at me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:292)
[22:07:59 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:54)
[22:07:59 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:07:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:07:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:07:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:07:59 WARN]: Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.bukkit.Chunk.getX()" because "chunk" is null
[22:07:59 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[22:07:59 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
[22:07:59 WARN]:        at me.lucko.spark.common.platform.world.WorldStatisticsProvider.getWorldStatistics(WorldStatisticsProvider.java:65)
[22:07:59 WARN]:        ... 13 more
[22:07:59 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.Chunk.getX()" because "chunk" is null
[22:07:59 WARN]:        at me.lucko.spark.bukkit.BukkitWorldInfoProvider$BukkitChunkInfo.<init>(BukkitWorldInfoProvider.java:65)
[22:07:59 WARN]:        at me.lucko.spark.bukkit.BukkitWorldInfoProvider.poll(BukkitWorldInfoProvider.java:52)
[22:07:59 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[22:07:59 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:54)
[22:07:59 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:332)
[22:07:59 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:876)
[22:07:59 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:387)
[22:07:59 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:786)
[22:07:59 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer$2.run(MinecraftServer.java:674)
[22:07:59 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[22:07:59 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[22:07:59 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[22:07:59 WARN]:        ... 3 more

**Comment by freaky767** [comment]
I have also noticed in some occasions that /spark and its sub commands completely stop working until the server is restarted (?), however I'm not certain as to why because no stack traces appear.
