### ISSUE TITLE
Error in Purpur 1.19.2

### ISSUE THREAD

**Issue by NykeDev** [lucko/spark#262]
```
[11:09:25] [spark-asyncsampler-worker-thread/WARN]: me.lucko.spark.common.sampler.async.JfrParsingException: Error parsing JFR data from profiler output
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at spark.jar//me.lucko.spark.common.sampler.async.AsyncProfilerJob.aggregate(AsyncProfilerJob.java:215)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at spark.jar//me.lucko.spark.common.sampler.async.AsyncSampler.rotateProfilerJob(AsyncSampler.java:119)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at java.base/java.lang.Thread.run(Thread.java:858)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]: Caused by: java.lang.IllegalArgumentException: Zero key not allowed
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at spark.jar//me.lucko.spark.common.sampler.async.jfr.Dictionary.put(Dictionary.java:46)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at spark.jar//me.lucko.spark.common.sampler.async.jfr.JfrReader.readThreads(JfrReader.java:335)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at spark.jar//me.lucko.spark.common.sampler.async.jfr.JfrReader.readConstants(JfrReader.java:301)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at spark.jar//me.lucko.spark.common.sampler.async.jfr.JfrReader.readConstantPool(JfrReader.java:290)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at spark.jar//me.lucko.spark.common.sampler.async.jfr.JfrReader.readChunk(JfrReader.java:216)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at spark.jar//me.lucko.spark.common.sampler.async.jfr.JfrReader.<init>(JfrReader.java:80)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     at spark.jar//me.lucko.spark.common.sampler.async.AsyncProfilerJob.aggregate(AsyncProfilerJob.java:204)
[11:09:25] [spark-asyncsampler-worker-thread/WARN]:     ... 7 more
```

**Comment by NykeDev** [comment]
This error occurs when turning on /spark profiler
