### ISSUE TITLE
Sampling operation failed unexpectedly

### ISSUE THREAD

**Issue by x1p** [lucko/spark#28]
Noticed this exception when stopping sampler
```
spark sampler --stop
[16:44:39 INFO]: [⚡] The active sampling operation has been stopped! Uploading results...
[16:44:39 INFO]: [⚡] Sampling operation failed unexpectedly. Error: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@5b1860eb rejected from java.util.concurrent.ScheduledThreadPoolExecutor@55df95f8[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 175036]
[16:44:39 WARN]: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@5b1860eb rejected from java.util.concurrent.ScheduledThreadPoolExecutor@55df95f8[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 175036]
[16:44:39 WARN]: at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
[16:44:39 WARN]: at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
[16:44:39 WARN]: at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
[16:44:39 WARN]: at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
[16:44:39 WARN]: at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)
[16:44:39 WARN]: at me.lucko.spark.common.sampler.Sampler.run(Sampler.java:134)
[16:44:39 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:44:39 WARN]: at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
[16:44:39 WARN]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
[16:44:39 WARN]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
[16:44:39 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:44:39 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:44:39 WARN]: at java.lang.Thread.run(Thread.java:748)
[16:44:39 INFO]: [⚡] Sampling results:
[16:44:39 INFO]: https://sparkprofiler.github.io/#z42eF6Swf
```
Command used: spark sampler --only-ticks-over 500

Paper 1.13.2 build 650
Spark build 95

**Comment by lucko** [comment]
Safe to ignore the error for now.
