### ISSUE TITLE
java.lang.IllegalStateException: Another profiler is already active (/sparkc profiler start)

### ISSUE THREAD

**Issue by Lolothepro** [lucko/spark#283]
```
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: java.lang.IllegalStateException: Another profiler is already active: me.lucko.spark.common.sampler.async.AsyncProfilerJob@74dacfd7
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: 	at me.lucko.spark.common.sampler.async.AsyncProfilerJob.createNew(AsyncProfilerJob.java:63)
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: 	at me.lucko.spark.common.sampler.async.AsyncProfilerAccess.startNewProfilerJob(AsyncProfilerAccess.java:94)
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: 	at me.lucko.spark.common.sampler.async.AsyncSampler.start(AsyncSampler.java:81)
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: 	at me.lucko.spark.common.sampler.SamplerBuilder.start(SamplerBuilder.java:122)
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: 	at me.lucko.spark.common.command.modules.SamplerModule.profilerStart(SamplerModule.java:228)
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: 	at me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:131)
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: 	at me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:408)
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: 	at me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:317)
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:07:00] [spark-worker-pool-1-thread-2/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```
```
Uname -a
Linux 6.1.0-0.2-liquorix-amd64 #1 ZEN SMP PREEMPT_DYNAMIC liquorix 6.1-2ubuntu1~jammy (2022-12- x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lucko** [comment]
Some other background would be good.

Spark version? Platform version? what were you trying to do at the time?

**Comment by Lolothepro** [comment]
Spark 1.10.17, Ubuntu 22.04, GTX 1070, Ryzen 1600, RAM : 16 Go

**Comment by Lolothepro** [comment]
[latest.log](https://github.com/lucko/spark/files/10309667/latest.log)

**Comment by lucko** [comment]
Try running `/spark profiler cancel` before

**Comment by Lolothepro** [comment]
`[spark-worker-pool-1-thread-1/INFO]: [System] [CHAT] [⚡] There isn't an active profiler running.`
