### ISSUE TITLE
profiler causing chunk nullpointerexception

### ISSUE THREAD

**Issue by freaky767** [lucko/spark#286]
Java version 17
Custom TacoSpigot 1.8.8 fork

```
[01:19:21 WARN]: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[01:19:21 WARN]:        at me.lucko.spark.common.platform.world.AsyncWorldInfoProvider.get(AsyncWorldInfoProvider.java:68)
[01:19:21 WARN]:        at me.lucko.spark.common.platform.world.AsyncWorldInfoProvider.getCounts(AsyncWorldInfoProvider.java:84)
[01:19:21 WARN]:        at me.lucko.spark.common.sampler.window.WindowStatisticsCollector.measure(WindowStatisticsCollector.java:159)
[01:19:21 WARN]:        at me.lucko.spark.common.sampler.window.WindowStatisticsCollector.lambda$measureNow$0(WindowStatisticsCollector.java:108)
[01:19:21 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
[01:19:21 WARN]:        at me.lucko.spark.common.sampler.window.WindowStatisticsCollector.measureNow(WindowStatisticsCollector.java:108)
[01:19:21 WARN]:        at me.lucko.spark.common.sampler.async.AsyncSampler.rotateProfilerJob(AsyncSampler.java:111)
[01:19:21 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[01:19:21 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[01:19:21 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[01:19:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:19:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:19:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:19:21 WARN]: Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[01:19:21 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[01:19:21 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
[01:19:21 WARN]:        at me.lucko.spark.common.platform.world.AsyncWorldInfoProvider.get(AsyncWorldInfoProvider.java:66)
[01:19:21 WARN]:        ... 12 more
[01:19:21 WARN]: Caused by: java.lang.NullPointerException
```

and

```
[00:59:21 WARN]: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.bukkit.Chunk.getTileEntities()" because "chunk" is null
[00:59:21 WARN]:        at me.lucko.spark.common.platform.world.AsyncWorldInfoProvider.get(AsyncWorldInfoProvider.java:68)
[00:59:21 WARN]:        at me.lucko.spark.common.platform.world.AsyncWorldInfoProvider.getCounts(AsyncWorldInfoProvider.java:84)
[00:59:21 WARN]:        at me.lucko.spark.common.sampler.window.WindowStatisticsCollector.measure(WindowStatisticsCollector.java:159)
[00:59:21 WARN]:        at me.lucko.spark.common.sampler.window.WindowStatisticsCollector.lambda$measureNow$0(WindowStatisticsCollector.java:108)
[00:59:21 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
[00:59:21 WARN]:        at me.lucko.spark.common.sampler.window.WindowStatisticsCollector.measureNow(WindowStatisticsCollector.java:108)
[00:59:21 WARN]:        at me.lucko.spark.common.sampler.async.AsyncSampler.rotateProfilerJob(AsyncSampler.java:111)
[00:59:21 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[00:59:21 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[00:59:21 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[00:59:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:59:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:59:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:59:21 WARN]: Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.bukkit.Chunk.getTileEntities()" because "chunk" is null
[00:59:21 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[00:59:21 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
[00:59:21 WARN]:        at me.lucko.spark.common.platform.world.AsyncWorldInfoProvider.get(AsyncWorldInfoProvider.java:66)
[00:59:21 WARN]:        ... 12 more
[00:59:21 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.Chunk.getTileEntities()" because "chunk" is null
[00:59:21 WARN]:        at me.lucko.spark.bukkit.BukkitWorldInfoProvider.pollCounts(BukkitWorldInfoProvider.java:74)
[00:59:21 WARN]:        at me.lucko.spark.common.platform.world.AsyncWorldInfoProvider.lambda$async$0(AsyncWorldInfoProvider.java:54)
[00:59:21 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[00:59:21 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:54)
[00:59:21 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:332)
[00:59:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:876)
[00:59:21 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:387)
[00:59:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:786)
[00:59:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer$2.run(MinecraftServer.java:674)
[00:59:21 WARN]:        ... 6 more
```

**Comment by freaky767** [comment]
for more context: this is from background profiler, regular profiler does do this too.
