### ISSUE TITLE
Start java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by BingZi-233** [lucko/spark#291]
```java
[23:25:38] [Server thread/ERROR] [Minecraft]: Error occurred while enabling spark v1.10.26 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at me.lucko.spark.lib.adventure.platform.bukkit.CraftBukkitAccess$EntitySound_1_19_3.<clinit>(CraftBukkitAccess.java:193) ~[?:?]
	at me.lucko.spark.lib.adventure.platform.bukkit.CraftBukkitFacet$EntitySound_1_19_3.isSupported(CraftBukkitFacet.java:470) ~[?:?]
	at me.lucko.spark.lib.adventure.platform.facet.Facet.of(Facet.java:79) ~[?:?]
	at me.lucko.spark.lib.adventure.platform.bukkit.BukkitAudience.<clinit>(BukkitAudience.java:70) ~[?:?]
	at me.lucko.spark.lib.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:136) ~[?:?]
	at me.lucko.spark.lib.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:74) ~[?:?]
	at me.lucko.spark.lib.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:112) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_231]
	at me.lucko.spark.lib.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:110) ~[?:?]
	at me.lucko.spark.lib.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:99) ~[?:?]
	at me.lucko.spark.lib.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.lambda$build$1(BukkitAudiencesImpl.java:175) ~[?:?]
	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_231]
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_231]
	at me.lucko.spark.lib.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.build(BukkitAudiencesImpl.java:173) ~[?:?]
	at me.lucko.spark.lib.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:89) ~[?:?]
	at me.lucko.spark.lib.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53) ~[?:?]
	at me.lucko.spark.bukkit.BukkitSparkPlugin.onEnable(BukkitSparkPlugin.java:65) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-1b57158]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-1b57158]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-1b57158]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:436) [CraftServer.class:git-CatServer-1.12.2-1b57158]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-1b57158]
	at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:391) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:327) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:602) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```

**Comment by lucko** [comment]
Should be fixed already in the latest version
