### ISSUE TITLE
1.7.10 startup errors

### ISSUE THREAD

**Issue by SegoItCh** [lucko/spark#309]
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NullPointerException
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at me.lucko.spark.common.sampler.ThreadDumper$GameThread.get(ThreadDumper.java:93)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at me.lucko.spark.forge.plugin.Forge1710ServerSparkPlugin.getDefaultThreadDumper(Forge1710ServerSparkPlugin.java:84)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at me.lucko.spark.common.sampler.BackgroundSamplerManager.startSampler(BackgroundSamplerManager.java:106)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at me.lucko.spark.common.sampler.BackgroundSamplerManager.initialise(BackgroundSamplerManager.java:81)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at me.lucko.spark.common.SparkPlatform.enable(SparkPlatform.java:186)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at me.lucko.spark.forge.plugin.Forge1710SparkPlugin.enable(Forge1710SparkPlugin.java:61)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at me.lucko.spark.forge.plugin.Forge1710ServerSparkPlugin.register(Forge1710ServerSparkPlugin.java:51)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at me.lucko.spark.forge.Forge1710SparkMod.serverInit(Forge1710SparkMod.java:65)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:94)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[17:16:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by lucko** [comment]
Sorry, 1.7.10 is not a supported version.
