### ISSUE TITLE
[1.18.2 Fabric] where to download fabric-command-api-v2

### ISSUE THREAD

**Issue by MSandro** [lucko/spark#317]
![image](https://user-images.githubusercontent.com/10937159/234473551-d87af74c-2eed-4484-888e-bdbe8fe3ee6e.png)since the last update it requires a library which I can't find.

**Comment by wati2006** [comment]
I get the same crash on startup. Maybe it's because Fabric API (in which the fabric-command-api-v2 is) is different in 1.19 and it's not working in the backport.

![image](https://user-images.githubusercontent.com/76632019/235303387-9fb1df30-5c6d-47c6-a35f-c2d21bc913c0.png)

```
[14:51:09] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.19
[14:51:10] [main/WARN]: Mod resolution failed
[14:51:10] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE spark 1.10.38 {depends fabric-command-api-v2 @ [*]}, ROOT_FORCELOAD_SINGLE spark 1.10.38]
[14:51:10] [main/INFO]: Reason: [HARD_DEP spark 1.10.38 {depends fabric-command-api-v2 @ [*]}]
[14:51:10] [main/INFO]: Fix: add [add:fabric-command-api-v2 1 ([(-?,?)])], remove [], replace []
[14:51:10] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-command-api-v2, any version.
Unmet dependency listing:
	 - Mod 'spark' (spark) 1.10.38 requires any version of fabric-command-api-v2, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
```

**Comment by Qian-F** [comment]
same issue

**Comment by lucko** [comment]
I've pushed a fixed version, thanks for letting me know :)
