### ISSUE TITLE
--alloc-live-only bugged?

### ISSUE THREAD

**Issue by Landon-9999** [lucko/spark#328]
Every time I try and run the alloc profiler on Fabric 1.19.2 it throws this error. It's only with the --alloc-live-only flag as well. The normal --alloc flag by itself works fine

[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: me.lucko.spark.common.sampler.async.JfrParsingException: Error parsing JFR data from profiler output
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at me.lucko.spark.common.sampler.async.AsyncProfilerJob.aggregate(AsyncProfilerJob.java:217)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at me.lucko.spark.common.sampler.async.AsyncSampler.stop(AsyncSampler.java:187)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at me.lucko.spark.common.command.modules.SamplerModule.profilerStop(SamplerModule.java:398)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:141)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:430)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:339)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot read field "methods" because "stackTrace" is null
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at me.lucko.spark.common.sampler.async.ProfileSegment.parseSegment(ProfileSegment.java:68)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at me.lucko.spark.common.sampler.async.AsyncProfilerJob.readSegments(AsyncProfilerJob.java:249)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	at me.lucko.spark.common.sampler.async.AsyncProfilerJob.aggregate(AsyncProfilerJob.java:207)
[21:47:19] [spark-worker-pool-1-thread-3/INFO]: [STDERR]: 	... 11 more

**Comment by lucko** [comment]
Should be fixed
