### ISSUE TITLE
[1.10.37 1.19.2] Erros?

### ISSUE THREAD

**Issue by itsdinkd** [lucko/spark#329]
when i stop the profiler i keep getting this
(fabric 1.19.2, 1.10.37 spark)
```java
01:12:43] [ForkJoinPool.commonPool-worker-14/INFO]: [STDERR]: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@5657f4c5[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@5caf9fb5[Wrapped task = me.lucko.spark.common.sampler.java.JavaSampler$InsertDataTask@52686a50]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1355606b[Shutting down, pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 20813]
[01:12:43] [ForkJoinPool.commonPool-worker-14/INFO]: [STDERR]:  at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
[01:12:43] [ForkJoinPool.commonPool-worker-14/INFO]: [STDERR]:  at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
[01:12:43] [ForkJoinPool.commonPool-worker-14/INFO]: [STDERR]:  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
[01:12:43] [ForkJoinPool.commonPool-worker-14/INFO]: [STDERR]:  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
[01:12:43] [ForkJoinPool.commonPool-worker-14/INFO]: [STDERR]:  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:705)
[01:12:43] [ForkJoinPool.commonPool-worker-14/INFO]: [STDERR]:  at me.lucko.spark.common.sampler.java.JavaSampler.run(JavaSampler.java:136)
[01:12:43] [ForkJoinPool.commonPool-worker-14/INFO]: [STDERR]:  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[01:12:43] [ForkJoinPool.commonPool-worker-14/INFO]: [STDERR]:  at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[01:12:43] [ForkJoinPool.commonPool-worker-14/INFO]: [STDERR]:  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[01:12:43] [ForkJoinPool.commonPool-worker-14/INFO]: [STDERR]:  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:12:43] [ForkJoinPool.commonPool-worker-14/INFO]: [STDERR]:  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:12:43] [ForkJoinPool.commonPool-worker-14/INFO]: [STDERR]:  at java.base/java.lang.Thread.run(Thread.java:833)
[01:12:43] [spark-worker-pool-1-thread-1/INFO]: [⚡] Tick #706 included GC lasting 18 ms. (type = Young Gen)
[01:12:43] [spark-worker-pool-1-thread-3/WARN]: [me.lucko.spark.common.SparkPlatform#lambda$executeCommand$4] A command execution has not completed after 5 seconds, it might be stuck. Trace: 
  java.base@17.0.7/sun.nio.ch.Net.poll(Native Method)
  java.base@17.0.7/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:181)
  java.base@17.0.7/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:285)
  java.base@17.0.7/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
  java.base@17.0.7/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
  java.base@17.0.7/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
  java.base@17.0.7/java.net.Socket$SocketInputStream.read(Socket.java:966)
  java.base@17.0.7/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
  java.base@17.0.7/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
  java.base@17.0.7/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
  java.base@17.0.7/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1465)
  java.base@17.0.7/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1069)
  java.base@17.0.7/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
  java.base@17.0.7/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
  java.base@17.0.7/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
  java.base@17.0.7/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:824)
  java.base@17.0.7/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759)
  java.base@17.0.7/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
  java.base@17.0.7/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
  java.base@17.0.7/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3243)
  java.base@17.0.7/sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:261)
  me.lucko.spark.common.util.BytebinClient.postContent(BytebinClient.java:72)
  me.lucko.spark.common.util.BytebinClient.postContent(BytebinClient.java:84)
  me.lucko.spark.common.command.modules.SamplerModule.handleOpen(SamplerModule.java:473)
  me.lucko.spark.common.command.modules.SamplerModule.profilerOpen(SamplerModule.java:355)
  me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:126)
  me.lucko.spark.common.command.modules.SamplerModule$$Lambda$29762/0x0000000804c2df20.execute(Unknown Source)
  me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:430)
  me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:339)
  me.lucko.spark.common.SparkPlatform$$Lambda$33502/0x00000008052c7168.run(Unknown Source)
  java.base@17.0.7/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
  java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
[01:12:44] [spark-worker-pool-1-thread-4/INFO]: [⚡] Profiler live viewer:
[01:12:44] [spark-worker-pool-1-thread-4/INFO]: https://spark.lucko.me/HmmpCU7hHV
[01:12:44] [spark-worker-pool-1-thread-2/INFO]: [⚡] Tick #739 included GC lasting 12 ms. (type = Young Gen)
```

**Comment by lucko** [comment]
https://github.com/lucko/spark/commit/b443924a665574f21e05e115eafea6171b046a02
