### ISSUE TITLE
Spark lets open-parties-and-claims crash.

### ISSUE THREAD

**Issue by mrukas** [lucko/spark#344]
I'm not quite sure whats interfering here, but it appears that spark is crashing Fabric 1.20.1 when open-parties-and-claims is installed.

It is completely reproducible:

- Create a new Fabric 1.20.1 instance.
- Install open-parties-and-claims with its depencies (b0.19.0, problems starts arising with version b0.18.0).
- Everything works
- Install spark
- Minecraft crashes when creating and opening a world

I also commented to an issue in the OPAC github page. (https://github.com/thexaero/open-parties-and-claims/issues/299)

I get the following error:
`[08/07/2023 00:41:40 AM] java.lang.NoClassDefFoundError: me/lucko/fabric/api/permissions/v0/Options
[08/07/2023 00:41:40 AM] 	at xaero.pac.common.server.player.permission.impl.FabricPermissionsSystem.getIntPermission(FabricPermissionsSystem.java:50)
[08/07/2023 00:41:40 AM] 	at xaero.pac.common.server.claims.player.ServerPlayerClaimInfoManager.getPlayerBaseLimit(ServerPlayerClaimInfoManager.java:148)
[08/07/2023 00:41:40 AM] 	at xaero.pac.common.server.claims.ServerClaimsManager.getPlayerBaseForceloadLimit(ServerClaimsManager.java:354)
[08/07/2023 00:41:40 AM] 	at xaero.pac.common.server.claims.forceload.ForceLoadTicketManager.updateTicketsFor(ForceLoadTicketManager.java:131)
[08/07/2023 00:41:40 AM] 	at xaero.pac.common.server.player.PlayerLoginHandler.handlePreWorldJoin(PlayerLoginHandler.java:61)
[08/07/2023 00:41:40 AM] 	at xaero.pac.common.server.player.data.api.ServerPlayerDataAPI.from(ServerPlayerDataAPI.java:87)
[08/07/2023 00:41:40 AM] 	at xaero.pac.common.event.CommonEvents.onPlayerLogIn(CommonEvents.java:168)
[08/07/2023 00:41:40 AM] 	at xaero.pac.common.event.CommonEventsFabric.onPlayerLogIn(CommonEventsFabric.java:132)
[08/07/2023 00:41:40 AM] 	at net.minecraft.class_3324.handler$zmm000$openpartiesandclaims$onPlaceNewPlayer(class_3324.java:3028)
[08/07/2023 00:41:40 AM] 	at net.minecraft.class_3324.method_14570(class_3324.java:307)
[08/07/2023 00:41:40 AM] 	at net.minecraft.class_3248.method_33800(class_3248.java:131)
[08/07/2023 00:41:40 AM] 	at net.minecraft.class_3248.method_14384(class_3248.java:118)
[08/07/2023 00:41:40 AM] 	at net.minecraft.class_3248.redirect$zen000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563)
[08/07/2023 00:41:40 AM] 	at net.minecraft.class_3248.method_18784(class_3248.java:68)
[08/07/2023 00:41:40 AM] 	at net.minecraft.class_2535.method_10754(class_2535.java:259)
[08/07/2023 00:41:40 AM] 	at net.minecraft.class_3242.method_14357(class_3242.java:172)
[08/07/2023 00:41:40 AM] 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
[08/07/2023 00:41:40 AM] 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
[08/07/2023 00:41:40 AM] 	at net.minecraft.class_1132.method_3748(class_1132.java:105)
[08/07/2023 00:41:40 AM] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
[08/07/2023 00:41:40 AM] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[08/07/2023 00:41:40 AM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[08/07/2023 00:41:40 AM] Caused by: java.lang.ClassNotFoundException: me.lucko.fabric.api.permissions.v0.Options
[08/07/2023 00:41:40 AM] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[08/07/2023 00:41:40 AM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[08/07/2023 00:41:40 AM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
[08/07/2023 00:41:40 AM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
[08/07/2023 00:41:40 AM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[08/07/2023 00:41:40 AM] 	... 22 more`

**Comment by noah1510** [comment]
This seems to be a problem with https://github.com/lucko/fabric-permissions-api and is fixed in version 0.2.
Spark seems to use version 0.1 as bundled version by default.

Just download version 0.2 from the github releases and drop the file in your mods folder.
This seems to work for me.
