### ISSUE TITLE
Spark Profiler not opening due to a timeout

### ISSUE THREAD

**Issue by miclol** [lucko/spark#356]
This is from Spark 1.10.42 in Minecraft 1.20.1.
Traceback:
```
[22:30:02 INFO] [Netty Epoll Play IO Thread #0]: [BetterFabricConsole] miclol issued server command: /spark profiler open
[22:30:08 WARN] [spark-worker-pool-1-thread-4]: [spark] A command execution has not completed after 5 seconds, it might be stuck. Trace:
  java.base@17.0.4/jdk.internal.misc.Unsafe.park(Native Method)
  java.base@17.0.4/java.util.concurrent.locks.LockSupport.park(Unknown Source)
  java.base@17.0.4/java.util.concurrent.CompletableFuture$Signaller.block(Unknown Source)
  java.base@17.0.4/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
  java.base@17.0.4/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
  java.base@17.0.4/java.util.concurrent.CompletableFuture.waitingGet(Unknown Source)
  java.base@17.0.4/java.util.concurrent.CompletableFuture.join(Unknown Source)
  me.lucko.spark.lib.bytesocks.BytesocksClientImpl.connect(BytesocksClientImpl.java:84)
  me.lucko.spark.lib.bytesocks.BytesocksClientImpl.createAndConnect(BytesocksClientImpl.java:75)
  me.lucko.spark.common.ws.ViewerSocketConnection.<init>(ViewerSocketConnection.java:61)
  me.lucko.spark.common.ws.ViewerSocket.<init>(ViewerSocket.java:71)
  me.lucko.spark.common.command.modules.SamplerModule.handleOpen(SamplerModule.java:467)
  me.lucko.spark.common.command.modules.SamplerModule.profilerOpen(SamplerModule.java:355)
  me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:126)
  me.lucko.spark.common.command.modules.SamplerModule$$Lambda$5987/0x0000000801af71b8.execute(Unknown Source)
  me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:430)
  me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:339)
  me.lucko.spark.common.SparkPlatform$$Lambda$9469/0x000000080212d000.run(Unknown Source)
  java.base@17.0.4/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.base@17.0.4/java.util.concurrent.FutureTask.run(Unknown Source)
  java.base@17.0.4/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
  java.base@17.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.base@17.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.base@17.0.4/java.lang.Thread.run(Unknown Source)
[22:30:09 INFO] [spark-worker-pool-1-thread-3]: [LoggedPrintStream] [STDERR]: java.util.concurrent.CompletionException: java.net.http.HttpTimeoutException: request timed out
[22:30:09 INFO] [spark-worker-pool-1-thread-3]: [LoggedPrintStream] [STDERR]:   at java.base/java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
[22:30:09 INFO] [spark-worker-pool-1-thread-3]: [LoggedPrintStream] [STDERR]:   at java.base/java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
[22:30:09 INFO] [spark-worker-pool-1-thread-3]: [LoggedPrintStream] [STDERR]:   at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
[22:30:09 INFO] [spark-worker-pool-1-thread-3]: [LoggedPrintStream] [STDERR]:   at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
[22:30:09 INFO] [spark-worker-pool-1-thread-3]: [LoggedPrintStream] [STDERR]:   at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
[22:30:09 INFO] [spark-worker-pool-1-thread-3]: [LoggedPrintStream] [STDERR]:   at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Unknown Source)
[22:30:09 INFO] [spark-worker-pool-1-thread-3]: [LoggedPrintStream] [STDERR]:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:30:09 INFO] [spark-worker-pool-1-thread-3]: [LoggedPrintStream] [STDERR]:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22:30:09 INFO] [spark-worker-pool-1-thread-3]: [LoggedPrintStream] [STDERR]:   at java.base/java.lang.Thread.run(Unknown Source)
[22:30:09 INFO] [spark-worker-pool-1-thread-3]: [LoggedPrintStream] [STDERR]: Caused by: java.net.http.HttpTimeoutException: request timed out
[22:30:09 INFO] [spark-worker-pool-1-thread-3]: [LoggedPrintStream] [STDERR]:   at java.net.http/jdk.internal.net.http.ResponseTimerEvent.handle(Unknown Source)
[22:30:09 INFO] [spark-worker-pool-1-thread-3]: [LoggedPrintStream] [STDERR]:   at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(Unknown Source)
[22:30:09 INFO] [spark-worker-pool-1-thread-3]: [LoggedPrintStream] [STDERR]:   at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source)
```

**Comment by ThatProgrammerr** [comment]
+1 can confirm this is also happening to myself, and a few others in the Spark Discord have seen it. Seems to be random and some users have shown it still works for them, while others like myself haven't been able to get it to work once today.

**Comment by Edgeburn** [comment]
This is also happening to me

```
[15:29:00 WARN]: [spark] A command execution has not completed after 5 seconds, it might be stuck. Trace: 
  java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)
  java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
  java.base@17.0.8/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
  java.base@17.0.8/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
  java.base@17.0.8/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
  java.base@17.0.8/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
  java.base@17.0.8/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
  spark-1.10.43-bukkit.jar//me.lucko.spark.lib.bytesocks.BytesocksClientImpl.connect(BytesocksClientImpl.java:84)
  spark-1.10.43-bukkit.jar//me.lucko.spark.lib.bytesocks.BytesocksClientImpl.createAndConnect(BytesocksClientImpl.java:75)
  spark-1.10.43-bukkit.jar//me.lucko.spark.common.ws.ViewerSocketConnection.<init>(ViewerSocketConnection.java:61)
  spark-1.10.43-bukkit.jar//me.lucko.spark.common.ws.ViewerSocket.<init>(ViewerSocket.java:71)
  spark-1.10.43-bukkit.jar//me.lucko.spark.common.command.modules.SamplerModule.handleOpen(SamplerModule.java:467)
  spark-1.10.43-bukkit.jar//me.lucko.spark.common.command.modules.SamplerModule.profilerOpen(SamplerModule.java:355)
  spark-1.10.43-bukkit.jar//me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:126)
  spark-1.10.43-bukkit.jar//me.lucko.spark.common.command.modules.SamplerModule$$Lambda$12957/0x00007fca3e822960.execute(Unknown Source)
  spark-1.10.43-bukkit.jar//me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:430)
  spark-1.10.43-bukkit.jar//me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:339)
  spark-1.10.43-bukkit.jar//me.lucko.spark.common.SparkPlatform$$Lambda$15785/0x00007fca3def60d0.run(Unknown Source)
  org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
  org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
  com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
  java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
[15:29:00 WARN]: 	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
[15:29:00 WARN]: java.util.concurrent.CompletionException: java.net.http.HttpTimeoutException: request timed out
[15:29:00 WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
[15:29:00 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152)
[15:29:00 WARN]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[15:29:00 WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
[15:29:00 WARN]: 	at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:483)
[15:29:00 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:29:00 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:29:00 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:29:00 WARN]: Caused by: java.net.http.HttpTimeoutException: request timed out
[15:29:00 WARN]: 	at java.net.http/jdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:63)
[15:29:00 WARN]: 	at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1270)
[15:29:00 WARN]: 	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:899)
```

**Comment by ArkoSammy12** [comment]
I can confirm the same is happening for me. Fabric 1.20.1 server

```
spark profiler open
[22:51:33] [spark-worker-pool-1-thread-4/WARN] (spark) A command execution has not completed after 5 seconds, it might be stuck. Trace: 
  java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)
  java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
  java.base@17.0.8/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
  java.base@17.0.8/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
  java.base@17.0.8/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
  java.base@17.0.8/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
  java.base@17.0.8/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
  me.lucko.spark.lib.bytesocks.BytesocksClientImpl.connect(BytesocksClientImpl.java:84)
  me.lucko.spark.lib.bytesocks.BytesocksClientImpl.createAndConnect(BytesocksClientImpl.java:75)
  me.lucko.spark.common.ws.ViewerSocketConnection.<init>(ViewerSocketConnection.java:61)
  me.lucko.spark.common.ws.ViewerSocket.<init>(ViewerSocket.java:71)
  me.lucko.spark.common.command.modules.SamplerModule.handleOpen(SamplerModule.java:467)
  me.lucko.spark.common.command.modules.SamplerModule.profilerOpen(SamplerModule.java:355)
  me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:126)
  me.lucko.spark.common.command.modules.SamplerModule$$Lambda$8212/0x00007fd6653d6718.execute(Unknown Source)
  me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:430)
  me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:339)
  me.lucko.spark.common.SparkPlatform$$Lambda$14068/0x00007fd665d2db10.run(Unknown Source)
  java.base@17.0.8/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  java.base@17.0.8/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  java.base@17.0.8/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
  java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [⚡] An error occurred whilst opening the live profiler.
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [STDERR]: java.util.concurrent.CompletionException: java.net.http.HttpTimeoutException: request timed out
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [STDERR]:    at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [STDERR]:    at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [STDERR]:    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152)
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [STDERR]:    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [STDERR]:    at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [STDERR]:    at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:483)
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [STDERR]:    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [STDERR]:    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [STDERR]:    at java.base/java.lang.Thread.run(Thread.java:833)
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [STDERR]: Caused by: java.net.http.HttpTimeoutException: request timed out
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [STDERR]:    at java.net.http/jdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:63)
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [STDERR]:    at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1270)
[22:51:33] [spark-worker-pool-1-thread-2/INFO] (Minecraft) [STDERR]:    at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:899)
```

**Comment by krzysiekigry** [comment]
same

**Comment by Draghonir** [comment]
same
<img width="1016" alt="1" src="https://github.com/lucko/spark/assets/107469643/a96f98a3-aa1b-45d8-bcfd-4d1f58ff2be9">

**Comment by lrdcxdes** [comment]
```
[21:33:18 INFO]: lrdcxdes issued server command: /spark profiler open
[21:33:23 WARN]: [spark] A command execution has not completed after 5 seconds, it might be stuck. Trace: 
  java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)
  java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
  java.base@17.0.8/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
  java.base@17.0.8/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
  java.base@17.0.8/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
  java.base@17.0.8/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
  java.base@17.0.8/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
  spark-1.10.49-bukkit.jar//me.lucko.spark.lib.bytesocks.BytesocksClientImpl.connect(BytesocksClientImpl.java:84)
  spark-1.10.49-bukkit.jar//me.lucko.spark.lib.bytesocks.BytesocksClientImpl.createAndConnect(BytesocksClientImpl.java:75)
  spark-1.10.49-bukkit.jar//me.lucko.spark.common.ws.ViewerSocketConnection.<init>(ViewerSocketConnection.java:61)
  spark-1.10.49-bukkit.jar//me.lucko.spark.common.ws.ViewerSocket.<init>(ViewerSocket.java:71)
  spark-1.10.49-bukkit.jar//me.lucko.spark.common.command.modules.SamplerModule.handleOpen(SamplerModule.java:467)
  spark-1.10.49-bukkit.jar//me.lucko.spark.common.command.modules.SamplerModule.profilerOpen(SamplerModule.java:355)
  spark-1.10.49-bukkit.jar//me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:126)
  spark-1.10.49-bukkit.jar//me.lucko.spark.common.command.modules.SamplerModule$$Lambda$7216/0x00007f5bad525a60.execute(Unknown Source)
  spark-1.10.49-bukkit.jar//me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:430)
  spark-1.10.49-bukkit.jar//me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:339)
  spark-1.10.49-bukkit.jar//me.lucko.spark.common.SparkPlatform$$Lambda$8867/0x00007f5bad705658.run(Unknown Source)
  org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run()
  org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run()
  com.destroystokyo.paper.ServerSchedulerReportingWrapper.run()
  java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
[21:33:24 WARN]: java.util.concurrent.CompletionException: java.net.http.HttpTimeoutException: request timed out
[21:33:24 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
[21:33:24 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
[21:33:24 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152)
[21:33:24 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[21:33:24 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
[21:33:24 WARN]:        at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:483)
[21:33:24 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:33:24 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:33:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[21:33:24 WARN]: Caused by: java.net.http.HttpTimeoutException: request timed out
[21:33:24 WARN]:        at java.net.http/jdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:63)
[21:33:24 WARN]:        at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1270)
[21:33:24 WARN]:        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:899)
```

**Comment by KimpiegamesYT1** [comment]
Same happening for me!

**Comment by lucko** [comment]
Thanks :)

**Comment by miclol** [comment]
Can also confirm that it works for me.

**Comment by Draghonir** [comment]
work for me V1.10.50 thanks ;)

**Comment by sndmax** [comment]
Same issue for 1.19.2
```[16:03:47] [spark-worker-pool-1-thread-2/WARN] [spark/]: A command execution has not completed after 5 seconds, it might be stuck. Trace: 
  java.base@18.0.2.1/jdk.internal.misc.Unsafe.park(Native Method)
  java.base@18.0.2.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
  java.base@18.0.2.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
  java.base@18.0.2.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3464)
  java.base@18.0.2.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3435)
  java.base@18.0.2.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
  java.base@18.0.2.1/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
  TRANSFORMER/spark@1.10.37/me.lucko.spark.lib.bytesocks.BytesocksClientImpl.connect(BytesocksClientImpl.java:84)
  TRANSFORMER/spark@1.10.37/me.lucko.spark.lib.bytesocks.BytesocksClientImpl.createAndConnect(BytesocksClientImpl.java:75)
  TRANSFORMER/spark@1.10.37/me.lucko.spark.common.ws.ViewerSocketConnection.<init>(ViewerSocketConnection.java:61)
  TRANSFORMER/spark@1.10.37/me.lucko.spark.common.ws.ViewerSocket.<init>(ViewerSocket.java:71)
  TRANSFORMER/spark@1.10.37/me.lucko.spark.common.command.modules.SamplerModule.handleOpen(SamplerModule.java:467)
  TRANSFORMER/spark@1.10.37/me.lucko.spark.common.command.modules.SamplerModule.profilerOpen(SamplerModule.java:355)
  TRANSFORMER/spark@1.10.37/me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:126)
  TRANSFORMER/spark@1.10.37/me.lucko.spark.common.command.modules.SamplerModule$$Lambda$34353/0x0000000804287038.execute(Unknown Source)
  TRANSFORMER/spark@1.10.37/me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:430)
  TRANSFORMER/spark@1.10.37/me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:339)
  TRANSFORMER/spark@1.10.37/me.lucko.spark.common.SparkPlatform$$Lambda$40145/0x0000000804886000.run(Unknown Source)
  java.base@18.0.2.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  java.base@18.0.2.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  java.base@18.0.2.1/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
  java.base@18.0.2.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@18.0.2.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@18.0.2.1/java.lang.Thread.run(Thread.java:833)
[16:03:47] [spark-worker-pool-1-thread-1/INFO] [minecraft/MinecraftServer]: [⚡] An error occurred whilst opening the live profiler.```

**Comment by ThatProgrammerr** [comment]
> Same issue for 1.19.2
> 
> ```
>   java.base@18.0.2.1/jdk.internal.misc.Unsafe.park(Native Method)
>   java.base@18.0.2.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
>   java.base@18.0.2.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
>   java.base@18.0.2.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3464)
>   java.base@18.0.2.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3435)
>   java.base@18.0.2.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
>   java.base@18.0.2.1/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
>   TRANSFORMER/spark@1.10.37/me.lucko.spark.lib.bytesocks.BytesocksClientImpl.connect(BytesocksClientImpl.java:84)
>   TRANSFORMER/spark@1.10.37/me.lucko.spark.lib.bytesocks.BytesocksClientImpl.createAndConnect(BytesocksClientImpl.java:75)
>   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.ws.ViewerSocketConnection.<init>(ViewerSocketConnection.java:61)
>   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.ws.ViewerSocket.<init>(ViewerSocket.java:71)
>   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.command.modules.SamplerModule.handleOpen(SamplerModule.java:467)
>   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.command.modules.SamplerModule.profilerOpen(SamplerModule.java:355)
>   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:126)
>   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.command.modules.SamplerModule$$Lambda$34353/0x0000000804287038.execute(Unknown Source)
>   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:430)
>   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:339)
>   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.SparkPlatform$$Lambda$40145/0x0000000804886000.run(Unknown Source)
>   java.base@18.0.2.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
>   java.base@18.0.2.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>   java.base@18.0.2.1/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
>   java.base@18.0.2.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
>   java.base@18.0.2.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
>   java.base@18.0.2.1/java.lang.Thread.run(Thread.java:833)
> [16:03:47] [spark-worker-pool-1-thread-1/INFO] [minecraft/MinecraftServer]: [⚡] An error occurred whilst opening the live profiler.```
> ```

Have you updated to V1.10.50 or later?

**Comment by sndmax** [comment]
> > Same issue for 1.19.2
> > ```
> >   java.base@18.0.2.1/jdk.internal.misc.Unsafe.park(Native Method)
> >   java.base@18.0.2.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
> >   java.base@18.0.2.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
> >   java.base@18.0.2.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3464)
> >   java.base@18.0.2.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3435)
> >   java.base@18.0.2.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
> >   java.base@18.0.2.1/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
> >   TRANSFORMER/spark@1.10.37/me.lucko.spark.lib.bytesocks.BytesocksClientImpl.connect(BytesocksClientImpl.java:84)
> >   TRANSFORMER/spark@1.10.37/me.lucko.spark.lib.bytesocks.BytesocksClientImpl.createAndConnect(BytesocksClientImpl.java:75)
> >   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.ws.ViewerSocketConnection.<init>(ViewerSocketConnection.java:61)
> >   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.ws.ViewerSocket.<init>(ViewerSocket.java:71)
> >   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.command.modules.SamplerModule.handleOpen(SamplerModule.java:467)
> >   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.command.modules.SamplerModule.profilerOpen(SamplerModule.java:355)
> >   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:126)
> >   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.command.modules.SamplerModule$$Lambda$34353/0x0000000804287038.execute(Unknown Source)
> >   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:430)
> >   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:339)
> >   TRANSFORMER/spark@1.10.37/me.lucko.spark.common.SparkPlatform$$Lambda$40145/0x0000000804886000.run(Unknown Source)
> >   java.base@18.0.2.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> >   java.base@18.0.2.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> >   java.base@18.0.2.1/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> >   java.base@18.0.2.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> >   java.base@18.0.2.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> >   java.base@18.0.2.1/java.lang.Thread.run(Thread.java:833)
> > [16:03:47] [spark-worker-pool-1-thread-1/INFO] [minecraft/MinecraftServer]: [⚡] An error occurred whilst opening the live profiler.```
> > ```
> 
> Have you updated to V1.10.50 or later?

Nvm. Version for 1.20 works on 1.19.2
