### ISSUE TITLE
can not open profiler 

### ISSUE THREAD

**Issue by mat43211** [lucko/spark#361]
### Description

I am unable to open the profiler 

### Reproduction Steps

 /spark profiler start
 /spark profiler open

below is my logs
11:35:34
Ting_MD issued server command: /spark profiler info
11:35:38
Ting_MD issued server command: /spark profiler start
[?]: Starting a new profiler, please wait...
[spark]: The async-profiler engine is not supported for your os/arch (windows10/amd64), so the built-in Java engine will be used instead.
[?]: Profiler is now running! (built-in java)
[?]: It will run in the background until it is stopped by an admin.
[?]: To stop the profiler and upload the results, run:
[?]: /spark profiler stop
[?]: To view the profiler while it's running, run:
[?]: /spark profiler open
11:35:43
Ting_MD issued server command: /spark profiler open
WARN11:35:48
[spark]: A command execution has not completed after 5 seconds, it might be stuck. Trace:
Console11:35:48
java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method)
java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
java.base@17.0.8.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
java.base@17.0.8.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
java.base@17.0.8.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
java.base@17.0.8.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
java.base@17.0.8.1/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
57242-v489830__spark.jar//me.lucko.spark.lib.bytesocks.BytesocksClientImpl.connect(BytesocksClientImpl.java:84)
57242-v489830__spark.jar//me.lucko.spark.lib.bytesocks.BytesocksClientImpl.createAndConnect(BytesocksClientImpl.java:75)
57242-v489830__spark.jar//me.lucko.spark.common.ws.ViewerSocketConnection.<init>(ViewerSocketConnection.java:61)
57242-v489830__spark.jar//me.lucko.spark.common.ws.ViewerSocket.<init>(ViewerSocket.java:71)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule.handleOpen(SamplerModule.java:467)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule.profilerOpen(SamplerModule.java:355)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:126)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule$$Lambda$5672/0x000002559903ec20.execute(Unknown Source)
57242-v489830__spark.jar//me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:425)
57242-v489830__spark.jar//me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:334)
57242-v489830__spark.jar//me.lucko.spark.common.SparkPlatform$$Lambda$7313/0x00000255992ec738.run(Unknown Source)
org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)
WARN11:35:48
java.util.concurrent.CompletionException: java.net.http.HttpTimeoutException: request timed out
at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:483)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.http.HttpTimeoutException: request timed out
at java.net.http/jdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:63)
at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1270)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:899)
INFO11:35:52
Ting_MD issued server command: /spark profiler open
WARN11:35:57
[spark]: A command execution has not completed after 5 seconds, it might be stuck. Trace:
Console11:35:57
java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method)
java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
java.base@17.0.8.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
java.base@17.0.8.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
java.base@17.0.8.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
java.base@17.0.8.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
java.base@17.0.8.1/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
57242-v489830__spark.jar//me.lucko.spark.lib.bytesocks.BytesocksClientImpl.connect(BytesocksClientImpl.java:84)
57242-v489830__spark.jar//me.lucko.spark.lib.bytesocks.BytesocksClientImpl.createAndConnect(BytesocksClientImpl.java:75)
57242-v489830__spark.jar//me.lucko.spark.common.ws.ViewerSocketConnection.<init>(ViewerSocketConnection.java:61)
57242-v489830__spark.jar//me.lucko.spark.common.ws.ViewerSocket.<init>(ViewerSocket.java:71)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule.handleOpen(SamplerModule.java:467)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule.profilerOpen(SamplerModule.java:355)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:126)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule$$Lambda$5672/0x000002559903ec20.execute(Unknown Source)
57242-v489830__spark.jar//me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:425)
57242-v489830__spark.jar//me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:334)
57242-v489830__spark.jar//me.lucko.spark.common.SparkPlatform$$Lambda$7313/0x00000255992ec738.run(Unknown Source)
org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)
WARN11:35:57
java.util.concurrent.CompletionException: java.net.http.HttpTimeoutException: request timed out
at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:483)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.http.HttpTimeoutException: request timed out
at java.net.http/jdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:63)
at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1270)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:899)

### Expected Behaviour

it gives me an ip to see the live profiler

### Platform Information

* Minecraft Version: 1.20.1
* Platform Type: server
* Platform Brand: paper
* Platform Version: paper #172
* the server is managed by AMP made by cubecoders
* os windows 10 pro build 19045

### Spark Version

v489830

### Logs and Configs

11:35:34
Ting_MD issued server command: /spark profiler info
11:35:38
Ting_MD issued server command: /spark profiler start
[?]: Starting a new profiler, please wait...
[spark]: The async-profiler engine is not supported for your os/arch (windows10/amd64), so the built-in Java engine will be used instead.
[?]: Profiler is now running! (built-in java)
[?]: It will run in the background until it is stopped by an admin.
[?]: To stop the profiler and upload the results, run:
[?]: /spark profiler stop
[?]: To view the profiler while it's running, run:
[?]: /spark profiler open
11:35:43
Ting_MD issued server command: /spark profiler open
WARN11:35:48
[spark]: A command execution has not completed after 5 seconds, it might be stuck. Trace:
Console11:35:48
java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method)
java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
java.base@17.0.8.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
java.base@17.0.8.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
java.base@17.0.8.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
java.base@17.0.8.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
java.base@17.0.8.1/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
57242-v489830__spark.jar//me.lucko.spark.lib.bytesocks.BytesocksClientImpl.connect(BytesocksClientImpl.java:84)
57242-v489830__spark.jar//me.lucko.spark.lib.bytesocks.BytesocksClientImpl.createAndConnect(BytesocksClientImpl.java:75)
57242-v489830__spark.jar//me.lucko.spark.common.ws.ViewerSocketConnection.<init>(ViewerSocketConnection.java:61)
57242-v489830__spark.jar//me.lucko.spark.common.ws.ViewerSocket.<init>(ViewerSocket.java:71)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule.handleOpen(SamplerModule.java:467)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule.profilerOpen(SamplerModule.java:355)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:126)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule$$Lambda$5672/0x000002559903ec20.execute(Unknown Source)
57242-v489830__spark.jar//me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:425)
57242-v489830__spark.jar//me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:334)
57242-v489830__spark.jar//me.lucko.spark.common.SparkPlatform$$Lambda$7313/0x00000255992ec738.run(Unknown Source)
org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)
WARN11:35:48
java.util.concurrent.CompletionException: java.net.http.HttpTimeoutException: request timed out
at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:483)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.http.HttpTimeoutException: request timed out
at java.net.http/jdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:63)
at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1270)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:899)
INFO11:35:52
Ting_MD issued server command: /spark profiler open
WARN11:35:57
[spark]: A command execution has not completed after 5 seconds, it might be stuck. Trace:
Console11:35:57
java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method)
java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
java.base@17.0.8.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
java.base@17.0.8.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
java.base@17.0.8.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
java.base@17.0.8.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
java.base@17.0.8.1/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
57242-v489830__spark.jar//me.lucko.spark.lib.bytesocks.BytesocksClientImpl.connect(BytesocksClientImpl.java:84)
57242-v489830__spark.jar//me.lucko.spark.lib.bytesocks.BytesocksClientImpl.createAndConnect(BytesocksClientImpl.java:75)
57242-v489830__spark.jar//me.lucko.spark.common.ws.ViewerSocketConnection.<init>(ViewerSocketConnection.java:61)
57242-v489830__spark.jar//me.lucko.spark.common.ws.ViewerSocket.<init>(ViewerSocket.java:71)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule.handleOpen(SamplerModule.java:467)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule.profilerOpen(SamplerModule.java:355)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:126)
57242-v489830__spark.jar//me.lucko.spark.common.command.modules.SamplerModule$$Lambda$5672/0x000002559903ec20.execute(Unknown Source)
57242-v489830__spark.jar//me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:425)
57242-v489830__spark.jar//me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:334)
57242-v489830__spark.jar//me.lucko.spark.common.SparkPlatform$$Lambda$7313/0x00000255992ec738.run(Unknown Source)
org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)
WARN11:35:57
java.util.concurrent.CompletionException: java.net.http.HttpTimeoutException: request timed out
at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:483)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.http.HttpTimeoutException: request timed out
at java.net.http/jdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:63)
at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1270)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:899)

### Extra Details

amp has it own local host server on 127.0.0.1:8080 and 127.0.0.1:8081 maybe that is causing issues? but it worked before not problem

**Comment by camfsd** [comment]
Replicable. This error was originally intermittent in 1.18 but since updating it occurs 100% of the time.

## Platform Information

    Minecraft Version: 1.19.4
    Platform Type: server
    Platform Brand: paper
    Platform Version: git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)

## Spark Version
v1.10.34

## Logs and Configs
https://paste.md-5.net/jolerurize.cs

**Comment by RillSoji** [comment]
Experiencing the same issue. Running latest paper in 1.20.1. I can generally get a report just fine but trying to open the live profiler just dumps that ^ error.

**Comment by camfsd** [comment]
> Experiencing the same issue. Running latest paper in 1.20.1. I can generally get a report just fine but trying to open the live profiler just dumps that ^ error.

Update to the latest version.
