### ISSUE TITLE
An error occurred whilst opening the live profiler.

### ISSUE THREAD

**Issue by zekeflynn** [lucko/spark#366]
### Description

Getting "An error occurred whilst opening the live profiler." when attempting to use the live profiler.

### Reproduction Steps

Launched my server.

Typed /spark profiler open, after server loaded.

Got error message in console.

### Expected Behaviour

Console to produce a link for the live profiler.

### Platform Information

* Minecraft Version:  1.20.1
* Platform Type: server
* Platform Brand: Forge
* Platform Version: 47.1.46

### Spark Version

1.10.42

### Logs and Configs

> [03:35:53] [spark-worker-pool-1-thread-2/INFO] [minecraft/MinecraftServer]: [⚡ ] An error occurred whilst opening the live profiler.
> java.lang.RuntimeException: Request failed: (GET https://spark-usersockets.lucko.me/create) 429
at TRANSFORMER/spark@1.10.42/me.lucko.spark.lib.bytesocks.BytesocksClientImpl.createAndConnect(BytesocksClientImpl.java:67)
at TRANSFORMER/spark@1.10.42/me.lucko.spark.common.ws.ViewerSocketConnection.<init>(ViewerSocketConnection.java:61)at TRANSFORMER/spark@1.10.42/me.lucko.spark.common.ws.ViewerSocket.<init>(ViewerSocket.java:71)
at TRANSFORMER/spark@1.10.42/me.lucko.spark.common.command.modules.SamplerModule.handleOpen(SamplerModule.java:467)at TRANSFORMER/spark@1.10.42/me.lucko.spark.common.command.modules.SamplerModule.profilerOpen(SamplerModule.java:355)
at TRANSFORMER/spark@1.10.42/me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:126)at TRANSFORMER/spark@1.10.42/me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:430)at TRANSFORMER/spark@1.10.42/me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:339)at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zekeflynn** [comment]
Updated to 1.10.53 and didn't get the error anymore.
