### ISSUE TITLE
403 Forbidden when uploading results

### ISSUE THREAD

**Issue by phoenixlzx** [lucko/spark#38]
Hi there,

We are getting 403 forbidden when uploading results:

```
[14:34:58 INFO]: [⚡] The active sampling operation has been stopped! Uploading results...
[14:35:00 WARN]: [spark] Plugin spark v1.3.2 generated an exception while executing task 15274897
java.lang.RuntimeException: Request was unsuccessful: 403 - Forbidden
        at me.lucko.spark.common.util.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:41) ~[?:?]
        at me.lucko.spark.common.util.BytebinClient.postContent(BytebinClient.java:84) ~[?:?]
        at me.lucko.spark.common.command.modules.SamplerModule.lambda$handleUpload$5(SamplerModule.java:261) ~[?:?]
        at me.lucko.spark.common.command.modules.SamplerModule$$Lambda$5947.0000000000000000.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-"7bd0b6ab"]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-"7bd0b6ab"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-"7bd0b6ab"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:819) [?:1.8.0_232]
```

Anything we can do to solve this?

Thank you in advance.

**Comment by lucko** [comment]
Seems like maybe Cloudflare is blocking your connection, or maybe your antivirus/firewall or something like that? Not much I can do about it I'm afraid.
