### ISSUE TITLE
Antivirus Defender

### ISSUE THREAD

**Issue by Mifuyuu** [lucko/spark#427]
### Description

[17:39:29] [ServerMain/ERROR]: [SparkProviderSource] Purpur: Failed to download and install spark plugin
java.nio.file.FileSystemException: cache\spark.jar: Operation did not complete successfully because the file contains a virus or potentially unwanted software
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?]
	at java.nio.file.Files.readAllBytes(Files.java:3288) ~[?:?]
	at io.papermc.paper.plugin.provider.source.SparkProviderSource.registerProviders(SparkProviderSource.java:59) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at io.papermc.paper.plugin.provider.source.SparkProviderSource.registerProviders(SparkProviderSource.java:22) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:105) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at net.minecraft.server.Main.main(Main.java:126) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at org.bukkit.craftbukkit.Main.main(Main.java:330) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]

### Reproduction Steps

idk but today when i run server microsoft defender are alert.

### Expected Behaviour

plugin not load

### Platform Information

* Minecraft Version: 1.20.1
* Platform Type: server
* Platform Brand: purpur
* Platform Version: purpur-1.20.1

### Spark Version

v1.10.85

**Comment by Woolyenough** [comment]
This may be of relevance to you: https://www.spigotmc.org/threads/windows-defender-false-positives.639507/ 🤷🏼‍♂️
