### ISSUE TITLE
[PlaceholderAPI] Failed to load expansion class SparkPlaceholderExpansion

### ISSUE THREAD

**Issue by wpmidia** [lucko/spark#433]
### Description

I don't know what to do! '-'
Could you help me?

`[05:01:22 ERROR]: [PlaceholderAPI] Failed to load expansion class SparkPlaceholderExpansion (Is a dependency missing?)
java.lang.NoSuchMethodError: 'me.lucko.spark.api.placeholder.PlaceholderResolver me.lucko.spark.api.Spark.placeholders()'
        at me.lucko.spark.placeholders.SparkPlaceholderExpansion.register(SparkPlaceholderExpansion.java:32) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:193) ~[PlaceholderAPI-2.11.6.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$4(LocalExpansionManager.java:366) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[PlaceholderAPI-2.11.6.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]`

### Reproduction Steps

Error occur on server startup

### Expected Behaviour

No errors (?)

### Platform Information

* Minecraft Version: 1.20.4
* Platform Type: server
* Platform Brand: PaperSpigot
* Platform Version: paper-1.20.4-496

### Spark Version

v.1.10.71

### Logs and Configs

https://gist.github.com/wpmidia/b9f7ae041c3f8c972684f7993a49a8a2

**Comment by Woolyenough** [comment]
I also had this issue; updating spark fixed the issue for me.

**Comment by wpmidia** [comment]
> I also had this issue; updating spark fixed the issue for me.

Thanks! It worked! :)

**Comment by wpmidia** [comment]
> I also had this issue; updating spark fixed the issue for me.

Thanks! It worked! :)
