### ISSUE TITLE
Crash on forge 1.21 server start: Cannot invoke "net.minecraft.server.level.ServerLevel.getWorldBorder()" because "serverlevel2" is null 

### ISSUE THREAD

**Issue by Craftingcat99** [lucko/spark#440]
### Description

server crashes with fresh instance of forge 1.21-51.0.33 installed and spark as the only mod loaded.

### Reproduction Steps

Install forge 1.21 51.0.33 (latest version at time of writing) put spark-1.10.73-forge.jar in mods folder and launch server

### Expected Behaviour

Server not crashing

### Platform Information

* Minecraft Version: 1.21
* Platform Type: server
* Platform Brand: Forge
* Platform Version: Forge 1.21 51.0.33

### Spark Version

v.1.10.73

### Logs and Configs

https://gist.github.com/Craftingcat99/c7fe91a4480e53a49dfd46cf8988a1f7

### Extra Details

Same problem with antivirus disabled and older versions of forge installed

**Comment by TheeFlyingPenguin** [comment]
I had a forge server 1.21  51.0.29 it was crashing at the end with : Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'java.lang.Thread net.minecraft.server.MinecraftServer.m_6304_()'
	at TRANSFORMER/spark@1.10.73/me.lucko.spark.forge.plugin.ForgeServerSparkPlugin.<init>(ForgeServerSparkPlugin.java:101) ~[spark-1.10.73-forge.jar!/:?] {re:classloading}
	at TRANSFORMER/spark@1.10.73/me.lucko.spark.forge.plugin.ForgeServerSparkPlugin.register(ForgeServerSparkPlugin.java:77) ~[spark-1.10.73-forge.jar!/:?] {re:classloading}
	at TRANSFORMER/spark@1.10.73/me.lucko.spark.forge.ForgeSparkMod.serverInit(ForgeSparkMod.java:68) ~[spark-1.10.73-forge.jar!/:?] {re:classloading}
	at TRANSFORMER/spark@1.10.73/me.lucko.spark.forge.__ForgeSparkMod_serverInit_ServerAboutToStartEvent.invoke(.dynamic) ~[spark-1.10.73-forge.jar!/:?] {re:classloading,pl:eventbus:B}
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:48) ~[eventbus-6.2.8.jar!/:?] {}
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:304) ~[eventbus-6.2.8.jar!/:?] {}
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:290) ~[eventbus-6.2.8.jar!/:?] {}
	at TRANSFORMER/forge@51.0.29/net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:81) ~[forge-1.21-51.0.29-universal.jar!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:189) ~[forge-1.21-51.0.29-server.jar!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665) ~[forge-1.21-51.0.29-server.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[forge-1.21-51.0.29-server.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?] {}
so I did update the server to the latest version and has the same error :(
