### ISSUE TITLE
Spam Warning in console when completing  /spark sampler (during run and stop process)

### ISSUE THREAD

**Issue by EchocallingEarth** [lucko/spark#57]
The following warnings spammed the console when running and stopping /spark sampler to get the link and review timings.

```
_[20:31:38] [Server thread/INFO]: [⚡] There isn't an active sampling task running.
[20:32:07] [Server thread/INFO]: EchocallingEarth issued server command: /spark sampler
[20:32:07] [Server thread/INFO]: [⚡] Initializing a new profiler, please wait...
[20:32:07] [Server thread/INFO]: [⚡] Profiler now active!
[20:32:07] [Server thread/INFO]: [⚡] Use '/spark sampler --stop' to stop profiling and upload the results.
[20:35:16] [Craft Scheduler Thread - 22/WARN]: java.util.ConcurrentModificationException
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.HashMap$EntryIterator.next(HashMap.java:1479)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.HashMap$EntryIterator.next(HashMap.java:1477)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.HashMap.putMapEntries(HashMap.java:512)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.HashMap.<init>(HashMap.java:490)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at com.songoda.epicfarming.farming.levels.modules.ModuleAutoCollect.collectLivestock(ModuleAutoCollect.java:122)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at com.songoda.epicfarming.farming.levels.modules.ModuleAutoCollect.runFinal(ModuleAutoCollect.java:49)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at com.songoda.epicfarming.farming.levels.modules.Module.run(Module.java:47)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at com.songoda.epicfarming.tasks.FarmTask.lambda$run$3(FarmTask.java:107)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at com.songoda.epicfarming.tasks.FarmTask.run(FarmTask.java:105)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[20:35:16] [Craft Scheduler Thread - 22/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[20:37:44] [Server thread/INFO]: EchocallingEarth is now AFK
[20:44:06] [Server thread/INFO]: [⚡] TPS from last 5s, 10s, 1m, 5m, 15m:
[20:44:06] [Server thread/INFO]: [⚡]  *20.0, *20.0, *20.0, 20.0, 19.89
[20:44:06] [Server thread/INFO]: [⚡] 
[20:44:06] [Server thread/INFO]: [⚡] Tick durations (avg/min/max ms) from last 5s, 10s, 1m:
[20:44:06] [Server thread/INFO]: [⚡]  13.0/11.1/18.2, 13.1/10.5/21.8, 13.0/9.8/122.2
[20:44:06] [Server thread/INFO]: [⚡] 
[20:44:06] [Server thread/INFO]: [⚡] CPU usage from last 10s, 1m, 15m:
[20:44:06] [Server thread/INFO]: [⚡]  12%, 12%, 19%  (system)
[20:44:06] [Server thread/INFO]: [⚡]  16%, 16%, 23%  (process)
[20:52:40] [Server thread/INFO]: EchocallingEarth is no longer AFK
[20:54:27] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 6568ms or 131 ticks behind
[20:54:34] [Server thread/INFO]: EchocallingEarth issued server command: /gms
[20:54:37] [Server thread/INFO]: EchocallingEarth issued server command: /fly
[20:55:27] [Server thread/INFO]: EchocallingEarth issued server command: /ah
[20:56:13] [Server thread/INFO]: EchocallingEarth issued server command: /spark sampler --stop
[20:56:13] [Server thread/INFO]: [⚡] The active sampling operation has been stopped! Uploading results...
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.comphenix.protocol.injector.netty.EventLoopProxy from ProtocolLib v4.5.0 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class net.goldtreeservers.worldguardextraflags.listeners.WorldListener from WorldGuardExtraFlags v4.1.4 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.sk89q.worldguard.protection.managers.RegionManager from WorldGuard v7.0.2-SNAPSHOT;bf2593e which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class nl.pim16aap2.bigDoors.handlers.ChunkUnloadHandler from BigDoors vAlpha 0.1.8.18 (b436) which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.imdanix.caves.mobs.MobsManager from DangerousCaves v2.2.2;16 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible from LuckPerms v5.1.46 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.sk89q.worldedit.bukkit.BukkitWorld from WorldEdit v7.1.0;8e55131 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.morelaid.AcceptTheRules.Event.Events from AcceptTheRules v2.5 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class DqnTRLiLuUyhkGRHw3Oq3bDufmzmJWPLA3OCehjlT5Vosl4nyo4AaVxAbQKFPsaftaKz4ndYRIUgPlWUB4hWhBtaSBnB7itsBCpgblXONsh6UsMIxsAoR5Rxc2wiXHCjwxHp44sDRravbEU2MkyGfZofOm2Jj8AyoB3CcSmUuJ from leakBanking v0.9.4 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.bergerkiller.bukkit.mw.MWListener from My_Worlds v1.15.2-v1 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.bergerkiller.bukkit.common.MaterialProperty from BKCommonLib v1.15.2-v4 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.konsolas.aac.bY from AAC v4.3.12 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.Zrips.CMI.Modules.FlightCharge.FlightListener from CMI v8.6.26.9 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class n3kas.ae.enchanthandler.effects.WebWalkerEffect from AdvancedEnchantments v7.6.14 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class xzot1k.plugins.ds.core.Listeners from DisplayShops v1.5 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.gamingmesh.jobs.listeners.JobsListener from Jobs v4.15.11 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.ryanhamshire.GPFlags.listener.PlayerListener from GriefPreventionFlags v5.9.0 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.songoda.epicspawners.listeners.InteractListeners from EpicSpawners v6.3.15 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.phil14052.CustomCobbleGen.Events.PlayerEvents from CustomCobbleGen v1.4.0 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class org.mineacademy.chatcontrol.lib.fo.model.p from ChatControl v8.6.6 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.griefcraft.listeners.LWCBlockListener from LWC v2.2.5-cdffea1 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.songoda.epicfarming.listeners.InteractListeners from EpicFarming v3.0.19 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.rockyhawk.commandPanels.utils from CommandPanels v3.1.1 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:14] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.ryanhamshire.GriefPrevention.PlayerEventHandler from GriefPrevention v16.13.0 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.songoda.epicanchors.core.gui.GuiManager$GuiListener from EpicAnchors v1.4.8 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.songoda.epichoppers.core.gui.GuiManager$GuiListener from EpicHoppers v4.6.7 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.songoda.epiclevels.core.gui.GuiManager$GuiListener from EpicLevels vmaven-version-number which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.songoda.ultimatecatcher.core.gui.GuiManager$GuiListener from UltimateCatcher v1.3.6 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.songoda.ultimatefishing.core.gui.GuiManager$GuiListener from UltimateFishing v1.2.6 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.songoda.ultimatekits.core.gui.GuiManager$GuiListener from UltimateKits v2.6.5 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.songoda.ultimaterepairing.core.gui.GuiManager$GuiListener from UltimateRepairing v1.3.4 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.arcaniax.hdb.listener.InventoryListener from HeadDatabase v4.12.3 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.wolfyscript.utilities.api.inventory.InventoryAPI from WolfyUtilities v1.5.6.19 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.wolfyscript.customcrafting.listeners.AnvilListener from CustomCrafting v1.5.5.0 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.xanium.noplugin.ui.MenuListener from NoPlugins v7.2 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.vomarek.MessagesGUI.Events.GUIClickListener from MessagesGUI v3.0 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class sh99.iteminchat.Listener.AsyncInventoryChatListener from ItemInChatFree v1.9.3 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class fr.moribus.imageonmap.image.MapInitEvent from ImageOnMap v4.0-pre2 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.rabbitcompany.admingui.listeners.InventoryClickListener from AdminGUI-Premium v4.1.2 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.qKing12.AuctionMaster.meniu.MeniuEvents2 from AuctionMaster v2.2 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.songoda.ultimatetimber.manager.TreeFallManager from UltimateTimber v2.0.6 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.mylogo.chestlock.listeners.PlayerListener from ChestLockGui v3.0.0 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.ebonjaeger.perworldinventory.listener.player.PlayerGameModeChangeListener from PerWorldInventory v2.3.2 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class me.hexedhero.lp.listeners.Stopper from LimitPillagers v2.12.0 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.gmail.filoghost.holographicdisplays.listener.MainListener from HolographicDisplays v2.4.2 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:15] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.songoda.ultimatestacker.listeners.EntityListeners from UltimateStacker v1.11.14 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:16] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.divisionind.bprm.events.BackpackTrackEvents from BackpacksRemastered v2020.0.4 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:16] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.songoda.epicfurnaces.tasks.FurnaceTask from EpicFurnaces v4.5.7 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:16] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.songoda.epicheads.listeners.DeathListeners from EpicHeads v3.2.10 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:16] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.froobworld.avl.tasks.MainTask from VillagerOptimiser v1.1.2 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:16] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.haroldstudios.infoheads.bukkit.Metrics from InfoHeads v2.2.21 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:16] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class ca.tweetzy.cosmicvaults.core.inventory.TInventoryEventListener from CosmicVaults v2.0.3 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:17] [Craft Scheduler Thread - 74/WARN]: [spark] Loaded class com.flodoerr.item_chest_sorter.Listener from Item-Chest-Sorter v1.5.1 which is not a depend, softdepend or loadbefore of this plugin.
[20:56:19] [Craft Scheduler Thread - 74/INFO]: [⚡] Sampling results:
[20:56:19] [Craft Scheduler Thread - 74/INFO]: https://spark.lucko.me/#SjOU8xYiHh_
```

I am unsure if this is a Bug or what so I am reporting it and hoping that you will know the answer and a fix so we do not have a spammed console when using Spark. Thanks, I'll await your reply for further info etc.

**Comment by lucko** [comment]
The first `ConcurrentModificationException` error is unrelated to spark - seems to stem from `com.songoda.epicfarming` doing something stupid, I suggest uninstalling that and/or finding a replacement.

The `Loaded class x from y which is not a depend, softdepend or loadbefore of this plugin` warnings are just a pointless message printed by Spigot. I've tried to rationalise with md_5 on the subject and got nowhere. Just ignore them for now I suppose.
